trigger:
- main

jobs:

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: ubuntu2204_cpython
    image_name: Ubuntu-22.04
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    test_suites:
      all: venv/bin/pytest -n 2 -vvs

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: ubuntu2404_cpython
    image_name: Ubuntu-24.04
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    test_suites:
      all: venv/bin/pytest -n 2 -vvs

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: macos14_cpython
    image_name: macOS-14
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    test_suites:
      all: venv/bin/pytest -n 2 -vvs

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: macos15_cpython
    image_name: macOS-15
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    test_suites:
      all: venv/bin/pytest -n 2 -vvs

- template: etc/ci/azure-windows.yml
  parameters:
    job_name: windows2022_cpython
    image_name: windows-2022
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]

- template: etc/ci/azure-windows.yml
  parameters:
    job_name: windows2025_cpython
    image_name: windows-2025
    python_versions: ["3.10", "3.11", "3.12", "3.13", "3.14"]

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: ubuntu2204_latest_deps
    image_name: Ubuntu-22.04
    python_versions: ["3.12"]
    setup_steps:
      - bash: pip install -U pip wheel setuptools
      - bash: pip install -r requirements-dev.txt
    test_suites:
      all: venv/bin/pytest -n 2 -vvs

- template: etc/ci/azure-posix.yml
  parameters:
    job_name: ubuntu_latest_click_versions
    image_name: Ubuntu-22.04
    python_versions: ["3.12"]
    test_suites:
      # This will test all versions of Click from 7.0 to the latest in an isolated fashion.
      all: ./utils/test-click-versions.sh
